#!/bin/bash

browser=$(xdg-settings get default-web-browser)

send_notification() {
    # Send notification with dunst
    dunstify -u low -t 3000 'Default Browser Change' "$1"
}

set_default_browser() {
    send_notification "Default browser set to $1"
    xdg-settings set default-web-browser $1
}

[[ $browser == "firefox.desktop" ]] && set_default_browser google-chrome.desktop
[[ $browser == "google-chrome.desktop" ]] && set_default_browser firefox.desktop
