#!/bin/zsh
# Convert all images from WALLPAPER_DIR into dithered forms at DITHER_DIR

WALLPAPER_DIR=$HOME/Pictures/wallpapers/active
DITHER_DIR=$HOME/Pictures/wallpapers/dithered

# Dithers $1 (image file) to become $2
dither () {
	echo $1 $2
	convert $1 -dither Riemersma -colors 6 $2
}

for i in $WALLPAPER_DIR/*; do
	dither $i $DITHER_DIR/$(basename $i)
done
	

