#!/bin/zsh
#
# If it doesn't work, use share link from youtube

# High quality download
ffmpeg \
	-ss $2 -to $3 -i "$(youtube-dl -f bestvideo -g "$1")" \
	-ss $2 -to $3 -i "$(youtube-dl -f bestaudio -g "$1")" \
	-c:v libvpx-vp9 -b:v 1M -c:a libopus -b:a 128k \
	$4
du -h $4

# Scaled to lower web quality:
#ffmpeg \
	#-ss 2:50.265 -to 3:01.594 -i "$(youtube-dl -f bestvideo -g "https://youtu.be/blah")" \
	#-ss 2:50.265 -to 3:01.594 -i "$(youtube-dl -f bestaudio -g "https://youtu.be/blah")" \
	#-c:v libvpx-vp9 -b:v 0.33M -c:a libopus -b:a 96k \
	#/tmp/outtwo.webm


# https://dev.to/benjaminblack/use-ffmpeg-to-compress-and-convert-videos-458l

#  might be suboptimal
#  need to compare filesize before and after flags, also compare time neeeded to transcode

