#!/bin/bash

pactl load-module module-null-sink sink_name=Combined_Output sink_properties=device.description=Combined_Output

pactl load-module module-null-sink sink_name=Recorded_Sink sink_properties=device.description=Recorded_Sink

pactl load-module module-loopback source=0 sink=Combined_Output

#pactl load-module module-loopback sink=Combined_Output
#pactl load-module module-loopback source=5 sink=Combined_Output
pactl load-module module-loopback source=3 sink=Combined_Output

#pactl load-module module-loopback sink=0
#pactl load-module module-loopback source=5 sink=0
pactl load-module module-loopback source=3 sink=0
